import { revalidateContentSeo } from "@/lib/content-revalidate";
import { notify } from "@/lib/notifications";
import { fetchWithBackoff } from "@/lib/automation/backoff";
export type PublishContext = { slug: string; url: string; pageType: string; ticketType?: string };
export type PublishStep = "revalidate" | "indexnow" | "google_indexing" | "gbp_post" | "notice";
export type PublishAdapters = { revalidate?: (context: PublishContext) => Promise<void> | void; indexNow?: (context: PublishContext) => Promise<void>; googleIndexing?: (context: PublishContext) => Promise<void>; gbpPost?: (context: PublishContext) => Promise<void>; notice?: (context: PublishContext) => Promise<void> };
export async function indexNow(context: PublishContext) { const key = process.env.INDEXNOW_KEY; if (!key) throw new Error("INDEXNOW_KEY is not configured."); const response = await fetchWithBackoff(fetch, "https://api.indexnow.org/indexnow", { method: "POST", headers: { "content-type": "application/json; charset=utf-8" }, body: JSON.stringify({ host: new URL(context.url).host, key, keyLocation: `${new URL(context.url).origin}/${key}.txt`, urlList: [context.url] }) }); if (!response.ok) throw new Error(`IndexNow failed (${response.status}).`); }
export async function publishNotice(context: PublishContext) { const chatId = process.env.TELEGRAM_ADMIN_CHAT_ID; if (chatId) await notify({ telegramChatId: chatId, preferences: { email: false, inApp: false } }, "page_published", { title: context.slug, link: context.url }); }
export async function runPublishSideEffects(context: PublishContext, adapters: PublishAdapters = {}) { const steps: Array<[PublishStep, () => Promise<void> | void]> = [["revalidate", () => adapters.revalidate?.(context) ?? revalidateContentSeo(context.slug)], ["indexnow", () => adapters.indexNow?.(context) ?? indexNow(context)], ["google_indexing", () => adapters.googleIndexing?.(context) ?? Promise.reject(new Error("Google Indexing adapter is not configured."))]]; if (context.pageType === "clinic" || context.ticketType === "gbp_post") steps.push(["gbp_post", () => adapters.gbpPost?.(context) ?? Promise.reject(new Error("GBP post adapter is not configured."))]); steps.push(["notice", () => adapters.notice?.(context) ?? publishNotice(context)]); const results: Array<{ step: PublishStep; ok: boolean; error?: string }> = []; for (const [step, execute] of steps) try { await execute(); results.push({ step, ok: true }); console.info("[publish-side-effect]", step, "completed"); } catch (error) { results.push({ step, ok: false, error: error instanceof Error ? error.message : "Publish step failed." }); console.error("[publish-side-effect]", step, error); } return results; }
