import { describe, expect, it } from "vitest";
import { runPublishSideEffects } from "./publish-effects";
import { handleReviewReceived, type Review, type ReviewReplyStore } from "./review-replies";
const review: Review = { id: "review-1", clinicId: "clinic-1", clinic: "Rohini", rating: 3, text: "Not happy", manager: { id: "manager", name: "Manager" } };
describe("publish and review safety", () => {
  it("continues ordered publication side effects after an IndexNow failure", async () => { const calls: string[] = []; const results = await runPublishSideEffects({ slug: "bera-test", url: "https://www.hearinghope.in/bera-test", pageType: "clinic" }, { revalidate: async () => { calls.push("revalidate"); }, indexNow: async () => { calls.push("indexnow"); throw new Error("down"); }, googleIndexing: async () => { calls.push("google"); }, gbpPost: async () => { calls.push("gbp"); }, notice: async () => { calls.push("notice"); } }); expect(calls).toEqual(["revalidate", "indexnow", "google", "gbp", "notice"]); expect(results.find((result) => result.step === "indexnow")).toMatchObject({ ok: false }); });
  it("never auto-publishes a 3-star review and alerts the manager", async () => { const tickets: unknown[] = []; let published = 0; let notifications = 0; let emails = 0; const store: ReviewReplyStore = { createTicket: async (_review, reply) => { tickets.push(reply); }, setAutoPublished: async () => { throw new Error("must not auto-publish"); } }; const result = await handleReviewReceived(review, store, { generate: async () => ({ replyText: "We are sorry to hear this.", escalate: false, escalationReason: "" }), publish: async () => { published += 1; }, notify: async () => { notifications += 1; }, emailEscalation: async () => { emails += 1; } }); expect(result).toEqual({ autoPublished: false }); expect(published).toBe(0); expect(tickets).toHaveLength(1); expect(notifications).toBe(1); expect(emails).toBe(1); });
  it("auto-publishes only a safe 4-star reply through the mocked GBP client", async () => { let published = 0; let status = ""; const store: ReviewReplyStore = { createTicket: async () => { throw new Error("must not ticket"); }, setAutoPublished: async () => { status = "auto_published"; } }; const result = await handleReviewReceived({ ...review, rating: 4 }, store, { generate: async () => ({ replyText: "Thank you for visiting Hearing Hope.", escalate: false, escalationReason: "" }), publish: async () => { published += 1; }, notify: async () => {}, emailEscalation: async () => {} }); expect(result).toEqual({ autoPublished: true }); expect(published).toBe(1); expect(status).toBe("auto_published"); });
  it("creates a human ticket when the provider is manual or quota-capped", async () => { const tickets: unknown[] = []; let published = 0; const store: ReviewReplyStore = { createTicket: async (_review, reply) => { tickets.push(reply); }, setAutoPublished: async () => { published += 1; } }; const result = await handleReviewReceived({ ...review, rating: 5 }, store, { generate: async () => { throw new Error("Daily Gemini cap reached; use manual copy-paste."); }, publish: async () => { published += 1; }, notify: async () => {}, emailEscalation: async () => {} }); expect(result).toEqual({ autoPublished: false }); expect(published).toBe(0); expect(tickets).toHaveLength(1); });
});
