import { createServiceSupabaseClient } from "@/lib/supabase/service";
import { normalizeQuestion } from "@/lib/automation/content-rules";
import type { GscRow, JobName, JobStore, JobSummary, QuestionCandidate, WebVital } from "./types";

export class SupabaseJobStore implements JobStore {
  private db() { return createServiceSupabaseClient(); }
  async start(jobName: JobName) { const { data, error } = await this.db().from("job_runs").insert({ job_name: jobName }).select("id").single(); if (error) throw new Error(error.message); return String(data.id); }
  async finish(id: string, summary: JobSummary) { const { error } = await this.db().from("job_runs").update({ finished_at: new Date().toISOString(), status: summary.status, items_processed: summary.itemsProcessed, llm_requests_used: summary.llmRequestsUsed, errors: summary.errors, notes: summary.notes }).eq("id", id); if (error) throw new Error(error.message); }
  async upsertGsc(rows: GscRow[]) { if (!rows.length) return 0; const { error } = await this.db().from("signals_search_console").upsert(rows.map((row) => ({ date: row.date, page_url: row.pageUrl, query: row.query, country: row.country, device: row.device, clicks: row.clicks, impressions: row.impressions, ctr: row.ctr, position: row.position })), { onConflict: "date,page_url,query,country,device" }); if (error) throw new Error(error.message); return rows.length; }
  async upsertVital(vital: WebVital) { const { error } = await this.db().from("signals_web_vitals").upsert({ date: new Date().toISOString().slice(0, 10), url: vital.url, strategy: vital.strategy, lcp: vital.lcp, inp: vital.inp, cls: vital.cls, performance_score: vital.performanceScore, raw_json: vital.raw }, { onConflict: "date,url,strategy" }); if (error) throw new Error(error.message); }
  async latestVital(url: string, strategy: "mobile" | "desktop") { const { data, error } = await this.db().from("signals_web_vitals").select("url,strategy,lcp,inp,cls,performance_score,raw_json").eq("url", url).eq("strategy", strategy).order("date", { ascending: false }).limit(1).maybeSingle(); if (error) throw new Error(error.message); return data ? { url: data.url, strategy: data.strategy as "mobile" | "desktop", lcp: data.lcp, inp: data.inp, cls: data.cls, performanceScore: data.performance_score, raw: data.raw_json as Record<string, unknown> } : null; }
  async questionQueries() { const { data, error } = await this.db().from("signals_search_console").select("query,impressions").gte("date", new Date(Date.now() - 7 * 864e5).toISOString().slice(0, 10)); if (error) throw new Error(error.message); return (data ?? []).filter((row) => /\?|\b(how|what|why|can|does|is|cost|price|near me|vs)\b/i.test(row.query)).map((row) => ({ question: row.query, source: "gsc" as const, volumeHint: row.impressions })); }
  async staffQuestions() { const { data, error } = await this.db().from("signals_questions").select("question,volume_hint").eq("source", "staff"); if (error) throw new Error(error.message); return (data ?? []).map((row) => ({ question: row.question, source: "staff" as const, volumeHint: row.volume_hint ?? 0 })); }
  async upsertQuestion(candidate: QuestionCandidate) { const normalized = normalizeQuestion(candidate.question); const { data, error } = await this.db().from("signals_questions").select("id,seen_count").eq("normalized_question", normalized).maybeSingle(); if (error) throw new Error(error.message); if (data) { const update = await this.db().from("signals_questions").update({ seen_count: Number(data.seen_count) + 1, last_seen_at: new Date().toISOString() }).eq("id", data.id); if (update.error) throw new Error(update.error.message); return; } const insert = await this.db().from("signals_questions").insert({ question: candidate.question, normalized_question: normalized, source: candidate.source, volume_hint: candidate.volumeHint ?? 0 }); if (insert.error) throw new Error(insert.error.message); }
}
