import { createServiceSupabaseClient } from "@/lib/supabase/service";
import type { DecisionCandidate, DecisionInput } from "./types";
import type { DecisionReviewer, DecisionStore, StoredDecisionTicket } from "./engine";

export class SupabaseDecisionStore implements DecisionStore {
  private readonly db = createServiceSupabaseClient();
  async loadInput(): Promise<DecisionInput> {
    const since = new Date(Date.now() - 28 * 864e5).toISOString().slice(0, 10);
    const reviewSince = new Date(Date.now() - 30 * 864e5).toISOString();
    const [pages, queries, questions, competitors, visibility, clinics, reviews] = await Promise.all([
      this.db.from("content_pages").select("id,slug,page_type,title,body_markdown,faq_items,json_ld,reviewed_by_id,last_content_update_at").eq("status", "published"),
      this.db.from("signals_search_console").select("query,impressions,ctr,position,page_url").gte("date", since), this.db.from("signals_questions").select("id,question,seen_count,source"), this.db.from("signals_competitors").select("url,title,first_seen_at"), this.db.from("signals_ai_visibility").select("question,our_domain_cited,competitor_domains_cited").order("date"), this.db.from("clinics").select("id,name,gbp_review_link"), this.db.from("signals_gbp_reviews").select("clinic_id,created_at").gte("created_at", reviewSince),
    ]);
    for (const result of [pages, queries, questions, competitors, visibility, clinics, reviews]) if (result.error) throw new Error(result.error.message);
    const impressions = new Map<string, number>();
    for (const row of queries.data ?? []) impressions.set(String(row.page_url), (impressions.get(String(row.page_url)) ?? 0) + Number(row.impressions));
    const reviewCounts = new Map<string, number>(); for (const row of reviews.data ?? []) reviewCounts.set(String(row.clinic_id), (reviewCounts.get(String(row.clinic_id)) ?? 0) + 1);
    return { now: new Date(), pages: (pages.data ?? []).map((row) => ({ id: String(row.id), slug: String(row.slug), pageType: row.page_type as DecisionInput["pages"][number]["pageType"], title: String(row.title), bodyMarkdown: String(row.body_markdown), faqItems: Array.isArray(row.faq_items) ? row.faq_items as Array<{ question: string; answer: string }> : [], jsonLd: row.json_ld, reviewedById: row.reviewed_by_id ? String(row.reviewed_by_id) : null, updatedAt: String(row.last_content_update_at), impressions: impressions.get(`${process.env.SITE_URL ?? "https://www.hearinghope.in"}/${row.slug}`) ?? 0 })), searchQueries: (queries.data ?? []).map((row) => ({ query: String(row.query), impressions: Number(row.impressions), ctr: Number(row.ctr), position: Number(row.position) })), questions: (questions.data ?? []).map((row) => ({ id: String(row.id), question: String(row.question), seenCount: Number(row.seen_count), source: row.source as "gsc" | "reddit" | "staff" })), competitors: (competitors.data ?? []).map((row) => ({ url: String(row.url), title: String(row.title), firstSeenAt: String(row.first_seen_at) })), aiVisibility: (visibility.data ?? []).map((row) => ({ question: String(row.question), ourDomainCited: Boolean(row.our_domain_cited), competitorCited: Array.isArray(row.competitor_domains_cited) && row.competitor_domains_cited.length > 0 })), clinics: (clinics.data ?? []).map((row) => ({ id: String(row.id), name: String(row.name), reviewCount30d: reviewCounts.get(String(row.id)) ?? 0, gbpReviewLink: String(row.gbp_review_link ?? ""), lastPostAt: null })), cwvRegressions: [] };
  }
  async reviewers(): Promise<DecisionReviewer[]> { const { data, error } = await this.db.from("team_members").select("id,staff_role,is_reviewer"); if (error) throw new Error(error.message); return (data ?? []).map((row) => ({ id: String(row.id), staffRole: row.staff_role as DecisionReviewer["staffRole"], isReviewer: Boolean(row.is_reviewer) })); }
  async listOpen(): Promise<StoredDecisionTicket[]> { const { data, error } = await this.db.from("content_tickets").select("id,type,status,priority_score,evidence,assigned_reviewer_id").in("status", ["open", "changes_requested", "generating"]); if (error) throw new Error(error.message); return (data ?? []).map((row) => ({ id: String(row.id), type: row.type as StoredDecisionTicket["type"], target: String((row.evidence as Record<string, unknown>)._dedupeTarget ?? ""), status: String(row.status), priorityScore: Number(row.priority_score), evidence: row.evidence as Record<string, unknown>, assignedReviewerId: row.assigned_reviewer_id ? String(row.assigned_reviewer_id) : null })); }
  async save(candidate: DecisionCandidate, reviewerId: string | null, existing?: StoredDecisionTicket) { const evidence = { ...candidate.evidence, _dedupeTarget: candidate.target }; const patch = { priority_score: Math.round(candidate.priorityScore), evidence, assigned_reviewer_id: reviewerId, reason: candidate.reason, target_page_id: candidate.targetPageId ?? null, target_clinic_id: candidate.targetClinicId ?? null, suggested_slug: candidate.suggestedSlug ?? "", suggested_page_type: candidate.suggestedPageType ?? "", target_keywords: candidate.targetKeywords ?? [] }; if (existing) { const { data, error } = await this.db.from("content_tickets").update(patch).eq("id", existing.id).select("id,type,status,priority_score,evidence,assigned_reviewer_id").single(); if (error) throw new Error(error.message); return { id: String(data.id), type: data.type as StoredDecisionTicket["type"], target: candidate.target, status: String(data.status), priorityScore: Number(data.priority_score), evidence: data.evidence as Record<string, unknown>, assignedReviewerId: data.assigned_reviewer_id ? String(data.assigned_reviewer_id) : null }; } const { data, error } = await this.db.from("content_tickets").insert({ type: candidate.type, status: "open", ...patch }).select("id,type,status,priority_score,evidence,assigned_reviewer_id").single(); if (error) throw new Error(error.message); return { id: String(data.id), type: data.type as StoredDecisionTicket["type"], target: candidate.target, status: String(data.status), priorityScore: Number(data.priority_score), evidence: data.evidence as Record<string, unknown>, assignedReviewerId: data.assigned_reviewer_id ? String(data.assigned_reviewer_id) : null }; }
}
