import { createServiceSupabaseClient } from "@/lib/supabase/service";
import { isSmtpConfigured } from "@/lib/leads/email";
import { telegramMessage, type NotificationType } from "./templates";

export type Recipient = { id?: string | null; name?: string; email?: string | null; telegramChatId?: string | null; preferences?: { email?: boolean; telegram?: boolean; inApp?: boolean } };
export type NotificationRecord = { recipientId: string | null; channel: "email" | "telegram" | "in_app"; type: NotificationType; payload: Record<string, unknown>; status: "sent" | "failed" | "pending"; error?: string };
export interface NotificationStore { record(row: NotificationRecord): Promise<void>; }
export interface Delivery { telegram?(chatId: string, text: string): Promise<void>; email?(email: string, subject: string, html: string): Promise<void>; }
export class SupabaseNotificationStore implements NotificationStore { async record(row: NotificationRecord) { const { error } = await createServiceSupabaseClient().from("notifications").insert({ recipient_id: row.recipientId, channel: row.channel, type: row.type, payload: row.payload, status: row.status, error: row.error ?? "", sent_at: row.status === "sent" ? new Date().toISOString() : null }); if (error) throw new Error(error.message); } }
export function configuredDelivery(): Delivery { return { telegram: async (chatId, text) => { const token = process.env.TELEGRAM_BOT_TOKEN; if (!token) throw new Error("TELEGRAM_BOT_TOKEN is not configured."); const response = await fetch(`https://api.telegram.org/bot${token}/sendMessage`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ chat_id: chatId, text, parse_mode: "MarkdownV2" }) }); if (!response.ok) throw new Error(`Telegram delivery failed (${response.status}).`); }, email: async (email, subject, html) => { if (!isSmtpConfigured()) throw new Error("SMTP is not configured."); const nodemailer = (await import("nodemailer")).default; const transport = nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: Number(process.env.SMTP_PORT) === 465, auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } }); await transport.sendMail({ from: process.env.SMTP_FROM || process.env.SMTP_USER, to: email, subject, text: html.replace(/<[^>]+>/g, " "), html }); } }; }
export async function notify(recipient: Recipient, type: NotificationType, payload: Record<string, unknown>, options: { store?: NotificationStore; delivery?: Delivery; emailOverride?: { subject: string; html: string } } = {}) { const store = options.store ?? new SupabaseNotificationStore(); const delivery = options.delivery ?? configuredDelivery(); const outcomes: NotificationRecord[] = []; const record = async (row: NotificationRecord) => { outcomes.push(row); await store.record(row); };
  // `pending` represents an unread in-app bell item. Opening the bell marks it sent/read.
  if (recipient.preferences?.inApp !== false) await record({ recipientId: recipient.id ?? null, channel: "in_app", type, payload, status: "pending" });
  if (recipient.preferences?.telegram !== false && recipient.telegramChatId) try { if (!delivery.telegram) throw new Error("Telegram delivery is not configured."); await delivery.telegram(recipient.telegramChatId, telegramMessage(type, payload)); await record({ recipientId: recipient.id ?? null, channel: "telegram", type, payload, status: "sent" }); } catch (error) { await record({ recipientId: recipient.id ?? null, channel: "telegram", type, payload, status: "failed", error: error instanceof Error ? error.message : "Telegram delivery failed." }); }
  if (recipient.preferences?.email !== false && recipient.email) try { if (!delivery.email) throw new Error("Email delivery is not configured."); const email = options.emailOverride ?? { subject: `Hearing Hope automation: ${type.replaceAll("_", " ")}`, html: `<p>${telegramMessage(type, payload).replaceAll("\n", "<br>")}</p>` }; await delivery.email(recipient.email, email.subject, email.html); await record({ recipientId: recipient.id ?? null, channel: "email", type, payload, status: "sent" }); } catch (error) { await record({ recipientId: recipient.id ?? null, channel: "email", type, payload, status: "failed", error: error instanceof Error ? error.message : "Email delivery failed." }); }
  return outcomes;
}
