import { createServiceSupabaseClient } from "@/lib/supabase/service";
import { getConfiguredLlmProvider } from "@/lib/generation/providers";
import { notify } from "@/lib/notifications";
import { computeReport, type ReportInput } from "./metrics";
import { monthlyNarrative, reportHtml, telegramSummary } from "./reporting";

type ReportType = "weekly" | "monthly";
export class SupabaseReportStore {
  private db() { return createServiceSupabaseClient(); }
  async input(): Promise<ReportInput> {
    const db = this.db(); const [gsc, insights, reviews, visibility, vitals, tickets, edits, usage, leads] = await Promise.all([db.from("signals_search_console").select("date,query,page_url,clicks,impressions"), db.from("signals_gbp_insights").select("date,calls,direction_requests,website_clicks,clinics(name)"), db.from("signals_gbp_reviews").select("created_at,rating,clinics(name)"), db.from("signals_ai_visibility").select("date,engine,our_domain_cited,competitor_domains_cited"), db.from("signals_web_vitals").select("url,strategy,lcp,inp,cls"), db.from("content_tickets").select("created_at,resolved_at,status"), db.from("review_edits").select("created_at,field"), db.from("llm_usage").select("date,requests"), db.from("form_leads").select("created_at,how_did_you_hear")]);
    for (const result of [gsc, insights, reviews, visibility, vitals, tickets, edits, usage, leads]) if (result.error) throw new Error(result.error.message);
    return { gsc: (gsc.data ?? []).map((row) => ({ date: String(row.date), query: String(row.query), pageUrl: String(row.page_url), clicks: Number(row.clicks), impressions: Number(row.impressions) })), insights: (insights.data ?? []).map((row) => ({ clinic: String((row.clinics as { name?: string } | null)?.name ?? "Unknown"), date: String(row.date), calls: Number(row.calls), directions: Number(row.direction_requests), websiteClicks: Number(row.website_clicks) })), reviews: (reviews.data ?? []).map((row) => ({ clinic: String((row.clinics as { name?: string } | null)?.name ?? "Unknown"), createdAt: String(row.created_at), rating: Number(row.rating) })), visibility: (visibility.data ?? []).map((row) => ({ date: String(row.date), engine: String(row.engine), cited: Boolean(row.our_domain_cited), competitors: Array.isArray(row.competitor_domains_cited) ? row.competitor_domains_cited.map(String) : [] })), vitals: (vitals.data ?? []).map((row) => ({ url: String(row.url), strategy: String(row.strategy), lcp: row.lcp === null ? null : Number(row.lcp), inp: row.inp === null ? null : Number(row.inp), cls: row.cls === null ? null : Number(row.cls) })), tickets: (tickets.data ?? []).map((row) => ({ createdAt: String(row.created_at), publishedAt: row.status === "published" ? String(row.resolved_at ?? "") || null : null, status: String(row.status) })), reviewEdits: (edits.data ?? []).map((row) => ({ createdAt: String(row.created_at), field: String(row.field) })), llmUsage: (usage.data ?? []).map((row) => ({ date: String(row.date), requests: Number(row.requests) })), attribution: (leads.data ?? []).map((row) => ({ createdAt: String(row.created_at), howDidYouHear: String(row.how_did_you_hear) })) };
  }
  async save(type: ReportType, metrics: Record<string, unknown>, narrative: string, html: string) { const period = metrics.period as { start: string; end: string }; const { error } = await this.db().from("automation_reports").upsert({ report_type: type, period_start: period.start, period_end: period.end, metrics, narrative, html }, { onConflict: "report_type,period_start,period_end" }); if (error) throw new Error(error.message); }
}
export async function runReport(type: ReportType, store = new SupabaseReportStore(), now = new Date()) {
  const days = type === "weekly" ? 7 : 30; const metrics = computeReport(await store.input(), now.toISOString().slice(0, 10), days); const narrative = type === "monthly" ? await monthlyNarrative(metrics, getConfiguredLlmProvider()) : { narrative: "", source: "template" as const }; const html = reportHtml(type, metrics, narrative.narrative); await store.save(type, metrics, narrative.narrative, html); await notify({ email: process.env.OWNER_EMAIL, telegramChatId: process.env.TELEGRAM_ADMIN_CHAT_ID, preferences: { inApp: false } }, "page_published", { title: `${type} report`, link: "/admin/automation/reports" }, { emailOverride: { subject: `Hearing Hope ${type} report`, html } }); return { metrics, narrative: narrative.source, telegram: telegramSummary(metrics) };
}
