import type { SupabaseClient } from "@supabase/supabase-js";
import { createServiceSupabaseClient } from "@/lib/supabase/service";
import type { DraftPage, GenerationStore, GenerationTicket } from "./run";

type Db = SupabaseClient;
function asTicket(row: Record<string, unknown>): GenerationTicket { return { id: String(row.id), type: String(row.type) as GenerationTicket["type"], status: String(row.status) as GenerationTicket["status"], priorityScore: Number(row.priority_score ?? 0), reason: String(row.reason ?? ""), evidence: (row.evidence as Record<string, unknown>) ?? {}, suggestedSlug: String(row.suggested_slug ?? ""), suggestedPageType: String(row.suggested_page_type ?? ""), targetKeywords: Array.isArray(row.target_keywords) ? row.target_keywords.map(String) : [], targetPageId: row.target_page_id ? String(row.target_page_id) : null, reviewNotes: "", attempts: Number(row.attempts ?? 0), pastedResponse: row.pasted_response }; }

export class SupabaseGenerationStore implements GenerationStore {
  constructor(private readonly db: Db = createServiceSupabaseClient()) {}
  async listReady(limit: number) { const { data, error } = await this.db.from("content_tickets").select("*").in("status", ["open", "changes_requested"]).order("priority_score", { ascending: false }).order("created_at", { ascending: true }).limit(limit); if (error) throw new Error(error.message); return (data ?? []).map((row) => asTicket(row as Record<string, unknown>)); }
  async getTicket(id: string) { const { data, error } = await this.db.from("content_tickets").select("*").eq("id", id).maybeSingle(); if (error) throw new Error(error.message); return data ? asTicket(data as Record<string, unknown>) : null; }
  async publishedLinks() { const { data, error } = await this.db.from("content_pages").select("slug,title").eq("status", "published").order("title").limit(200); if (error) throw new Error(error.message); return (data ?? []).map((row) => ({ slug: String(row.slug), title: String(row.title) })); }
  async existingPage(ticket: GenerationTicket) { if (!ticket.targetPageId) return null; const { data, error } = await this.db.from("content_pages").select("slug,page_type,title,meta_title,meta_description,answer_summary,body_markdown,faq_items,sources,internal_links,json_ld,review_notes").eq("id", ticket.targetPageId).maybeSingle(); if (error) throw new Error(error.message); if (!data) return null; return { slug: data.slug, pageType: data.page_type, title: data.title, metaTitle: data.meta_title, metaDescription: data.meta_description, answerSummary: data.answer_summary, bodyMarkdown: data.body_markdown, faqItems: data.faq_items, sources: data.sources, internalLinks: data.internal_links, jsonLd: data.json_ld, reviewNotes: data.review_notes }; }
  async updateTicket(id: string, patch: Record<string, unknown>) { const { error } = await this.db.from("content_tickets").update(patch).eq("id", id); if (error) throw new Error(error.message); }
  async createDraft(ticket: GenerationTicket, page: DraftPage) { const { data, error } = await this.db.from("content_pages").insert({ slug: page.slug, page_type: page.pageType, status: "draft", title: page.title, meta_title: page.metaTitle, meta_description: page.metaDescription, answer_summary: page.answerSummary, body_markdown: page.bodyMarkdown, faq_items: page.faqItems, sources: page.sources, internal_links: page.internalLinks, json_ld: page.jsonLd, generation_meta: page.generationMeta, priority_score: ticket.priorityScore, reviewed_by_id: null, reviewed_at: null }).select("id").single(); if (error) throw new Error(error.message); return String(data.id); }
  async attachProposal(ticket: GenerationTicket, proposal: unknown) { await this.updateTicket(ticket.id, { pasted_response: proposal }); }
}
